import { RouteInfo } from "./routeInfo";

export const navBardata: RouteInfo[] = [
    {
        routerLink: '/admin/dashboard',
        icon: 'B',
        label: 'Dashboard',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        subMenu: [],
    },
    {
        routerLink: '/admin/ecole/ecoleList',
        icon: 'B',
        label: 'Ecole',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        subMenu: [],
    },
    {
        routerLink: '/admin/anneeScolaire/listAnneeScolaire',
        icon: 'B',
        label: 'Année scolaire',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        subMenu: [],
    },
    {
        routerLink: '/admin/profiles/listProfile',
        icon: 'B',
        label: 'Profiles',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        subMenu: [],
    },
    {
        routerLink: '/admin/classes/allClasses',
        icon: 'B',
        label: 'Classes',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        subMenu: [],
    },
    {
        routerLink: '/admin/matieres/allMatieres',
        icon: 'B',
        label: 'Matières',
        class: 'menu-toggle',
        groupTitle: false,
        badge: '',
        badgeClass: '',
        role: ['Admin'],
        subMenu: [],
    },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Inscription',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Elèves',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Parents',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Professeurs',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Notes',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Bulletins',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '',
    //     icon: 'B',
    //     label: 'Retard et absence',
    //     class: 'menu-toggle',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '/admin/settings',
    //     icon: 'B',
    //     label: 'Settings',
    //     class: '',
    //     groupTitle: false,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // },
    // {
    //     routerLink: '/admin/messagerie',
    //     icon: 'B',
    //     label: 'Messagerie',
    //     class: 'menu-toggle',
    //     groupTitle: true,
    //     badge: '',
    //     badgeClass: '',
    //     role: ['Admin'],
    //     subMenu: [],
    // }
]